<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnwpsxp\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnwpsxp/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAnwpsxp.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAnwpsxp\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAnwpsxp\srcDevDebugProjectContainer([
    'container.build_hash' => 'Anwpsxp',
    'container.build_id' => 'd12914e4',
    'container.build_time' => 1604239760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnwpsxp');
